<?xml version="1.0"?>
<!DOCTYPE dico_verbnet_rolemapping [
  <!ELEMENT dico_verbnet_rolemapping (lexie+)>
  <!ATTLIST dico_verbnet_rolemapping lang (en|fr) #REQUIRED>
  <!ATTLIST dico_verbnet_rolemapping vn CDATA #REQUIRED>
  <!ELEMENT lexie  (role*)>
  <!ATTLIST lexie name  CDATA #REQUIRED>
  <!ATTLIST lexie lemma (ok|missing) 'ok'>
  <!ATTLIST lexie sense (ok|missing|metaphor|far-fetched) #REQUIRED>
  <!ATTLIST lexie vn    CDATA #IMPLIED>
  <!ATTLIST lexie alternations (ok|more|missing|more-missing) #IMPLIED>
  <!ATTLIST lexie roles (ok|more|missing|more-missing) #IMPLIED>
  <!ATTLIST lexie on CDATA #IMPLIED>
  <!ATTLIST lexie wn CDATA #IMPLIED>
  <!ELEMENT role   (#PCDATA)>
  <!ATTLIST role  name  CDATA #REQUIRED>
  <!ATTLIST role  vn    CDATA #REQUIRED>
]>
<dico_verbnet_rolemapping lang='en' vn='3.2'>
    <lexie name='abate.1' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='absorb.1' sense='missing' on='absorb.1' wn='absorb#4 absorb#6'>
    </lexie>
    <lexie name='accelerate.1a' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='accelerate.1b' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='accumulate.1' vn='herd-47.5.2' sense='ok' alternations='ok' roles='more-missing'>
        <role name='Patient' vn='Theme' />
        <role name='Location' vn='N/A' />
    </lexie>
    <lexie name='adapt.1' vn='adjut-26.9' sense='ok' alternations='more' roles='more'>
        <!-- VerbNet uses two roles for 'He.Agent adapted himself.Patient'
             while DicoEnviro would have used an indirect link. -->
        <role name='Patient' vn='Agent' />
        <role name='Cause' vn='Goal' />
    </lexie>
    <lexie name='affect.1' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='alter.1' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Agent' vn='Agent' />
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='amplify.1' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='burn.2' vn='other_cos-45.4-1' sense='ok' alternations='more' roles='more'>
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='capture.1' vn='steal-10.5' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Destination' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='capture.3' vn='steal-10.5' sense='ok' alternations='more' roles='more'>
        <role name='Destination' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='change.1a' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='change.1b' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Agent' vn='Agent' />
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='compensate.1' sense='missing'>
        <!-- We're talking about the very specific 'make up for' sense, which
             is not in VerbNet even though OntoNotes says it is in judgment-33.
             Am I being too strict here? -->
    </lexie>
    <lexie name='conserve.1' sense='missing'>
        <!-- only sense wn4 in VN (but OntoNotes gruops them all!) -->
    </lexie>
    <lexie name='consume.1' vn='consume-66' sense='ok' alternations='ok' roles='more'>
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Asset' />
    </lexie>
    <lexie name='contaminate.1' sense='missing' on='contaminate.1'>
        <!-- DicoEnviro only has one context. -->
    </lexie>
    <lexie name='convert.1' vn='turn-26.6.1' sense='ok' alternations='ok' roles='more'>
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Patient' />
        <role name='Result' vn='Result' />
    </lexie>
    <lexie name='cool.1a' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='cool.1b' vn='other_cos-45.4' sense='ok'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
        <role name='Agent' vn='Agent' />
    </lexie>
    <lexie name='damage.2' vn='destroy-44' sense='ok' alternations='ok' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='decline.1' vn='calibratable_cos-45.6-1' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='decrease.1a' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='decrease.1b' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='degrade.1' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='deplete.1' vn='cheat-10.6' sense='ok' alternations='more' roles='more'>
        <!-- I'm not sure if 10.6 is the correct place for deplete. -->
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Theme' />
        <role name='Agent' vn='Agent' />
    </lexie>
    <lexie name='deposit.2' vn='put-9.1' sense='ok'>
        <role name='Patient' vn='Theme' />
        <role name='Destination' vn='Destination' />
    </lexie>
    <lexie name='disappear.1' vn='disappearance-48.2' sense='ok' alternations='more' roles='more'>
        <!-- In this case, we do have a 'Initial_Location' role which is why
             VerbNet has more alternations and more roles, but this probably
             does not warrant creating a new class. -->
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='endanger.1' sense='missing' on='endanger.1'>
    </lexie>
    <lexie name='emit.1' sense='missing' on='emit.1'>
    </lexie>
    <lexie name='emit.2' sense='missing' on='emit.1'>
    </lexie>
    <lexie name='erode.1a' vn='entity_specific_cos-45.4' sense='ok' alternations='ok' roles='ok'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='evaporate.1' vn='other_cos-45.4' sense='ok' alternations='more' roles='more-missing'>
        <role name='Patient' vn='Patient' />
        <role name='Source' vn='N/A' />
    </lexie>
    <lexie name='flood.2' vn='fill-9.8' sense='ok' alternations='ok' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Location' vn='Destination' />
    </lexie>
    <lexie name='fluctuate.1' vn='calibratable_cos-45.6-1' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='freeze.1' vn='other_cos-45.4-1' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='generate.1a' vn='engender-27' sense='ok'>
        <role name='Instrument' vn='Cause' />
        <role name='Patient' vn='Theem' />
    </lexie>
    <lexie name='generate.1b' vn='engender-27' sense='ok' alternations='more' roles='more'>
        <role name='Agent' vn='Cause' />
        <role name='Instrument' vn='Cause' />
        <role name='Natural_force' vn='Cause' />
        <role name='Means' vn='Cause' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='grow.1' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='heat.2' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Instrument' vn='Instrument' />
        <role name='Means' vn='Instrument' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='impact.2' sense='missing' on='impact.1'>
    </lexie>
    <lexie name='increase.1a' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='increase.1b' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='influence.2' vn='force-59-1' sense='ok' alternations='more' roles='more'>
        <!-- As in release.1a, Cause and Agent are actually Agent. Why the
             distinction? -->
        <role name='Cause' vn='Agent' />
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='measure.1a' vn='register-54.1' sense='ok' alternations='ok' roles='more'>
        <role name='Instrument' vn='Agent ' />
        <role name='Patient' vn='Theme' />
        <role name='Means' vn='Agent' />
    </lexie>
    <lexie name='measure.1b' vn='register-54.1' sense='ok' alternations='ok' roles='more'>
        <role name='Instrument' vn='Agent ' />
        <role name='Agent' vn='Agent ' />
        <role name='Patient' vn='Theme' />
        <role name='Means' vn='Agent' />
        <role name='Method' vn='Agent' />
    </lexie>
    <lexie name='melt.1a' vn='other_cos-45.4-1' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='melt.1b' vn='other_cos-45.4-1' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='migrate.1' sense='missing' on='migrate.1'>
        <!-- The OntoNotes sense #2 isn't clear. From the examples, it seems to
             apply to 'digital' senses. -->
    </lexie>
    <lexie name='migrate.2' sense='missing'>
        <!-- The OntoNotes sense #2 isn't clear. From the examples, it seems to
             apply to 'digital' senses. -->
    </lexie>
    <lexie name='mitigate.1' vn='other_cos-45.4' sense='ok' alternations='ok' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='monitor.1' sense='ok' alternations='ok' roles='more'>
        <role name='Method' vn='Theme' />
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Agent' />
    </lexie>
    <lexie name='pollute.1b' vn='fill-9.8' sense='ok'>
        <role name='Cause' vn='Agent' />
        <role name='Destination' vn='Destination' />
        <role name='Agent' vn='Agent' />
    </lexie>
    <lexie name='predict.1a' vn='indicate-78' sense='ok' alternations='more' roles='more'>
        <role name='Method' vn='Cause' />
        <role name='Patient' vn='Topic' />
    </lexie>
    <lexie name='predict.1b' vn='indicate-78' sense='ok' alternations='more' roles='more'>
        <role name='Method' vn='Agent' />
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Topic' />
    </lexie>
    <lexie name='project.1a' vn='estimate-34.2' sense='ok' alternations='more' roles='more'>
        <role name='Method' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='project.1b' vn='estimate-34.2' sense='ok' alternations='more' roles='more'>
        <role name='Method' vn='Agent' />
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='protect.1' vn='defend-85' sense='ok' alternations='more-missing' roles='ok'>
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Theme' />
        <role name='Threat' vn='Co-Theme' />
    </lexie>
    <lexie name='recycle.1' sense='missing' on='recycle.1'>
    </lexie>
    <lexie name='release.1a' sense='missing' on='release.3' wn='release#5'>
        <!-- free-80 is close semantically, but none of the alternations we're
             interested in are here. Also, there's an issue with Cause and
             Agent which 1/ would both be 'Agent' in VerbNet's case 2/
             sometimes cause is more like a Circonstant. -->
    </lexie>
    <lexie name='release.1b' sense='missing' on='release.3' wn='release#5'>
        <!-- free-80 is close semantically, but none of the alternations we're
             interested in are here. Also, there's an issue with Cause and
             Agent which 1/ would both be 'Agent' in VerbNet's case 2/
             sometimes cause is more like a Circonstant. -->
    </lexie>
    <lexie name='reflect.1' sense='missing'>
        <!-- only figurative sense in VerbNet -->
    </lexie>
    <lexie name='retreat.1' vn='escape-51.1' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Theme' />
    </lexie>
    <!-- In those two cases, the issue is simply that VerbNet roles are found
         in Circonstant, and 'Patient' is the only 'Actant' -->
    <lexie name='rise.1' vn='calibratable_cos-45.6-1' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='rise.2' vn='calibratable_cos-45.6-1' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='sequester.1' vn='steal-10.5' sense='far-fetched' alternations='ok' roles='more'>
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='shift.1' vn='calibratable_cos-45.6-1' sense='ok' alternations='ok' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='shift.2' sense='missing'>
        <!-- Not clear what sense this is. TODO along with shift.1 -->
    </lexie>
    <lexie name='simulate.1' sense='missing'>
        <!-- I didn't find a fitting class yet. The fegning sense could fit. -->
    </lexie>
    <lexie name='sink.1' sense='missing'>
        <!-- Missing sense: this sense is about sinking to the ground (the real
             sense), while VerbNet only covers the metaphorical sense in class
             45. -->
    </lexie>
    <lexie name='stabilize.1a' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='stabilize.1b' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
        <role name='Means' vn='Instrument' />
    </lexie>
    <lexie name='supply.1' vn='fulfillig-13.4.1' sense='ok' alternations='ok' roles='ok'>
        <role name='Agent' vn='Agent' />
        <role name='Patient' vn='Theme' />
        <role name='Recipient' vn='Recipient' />
        <role name='Cause' vn='Agent' />
    </lexie>
    <lexie name='store.1b' vn='keep-15.2' sense='ok' alternations='ok' roles='more'>
        <!-- This is an interesting case of subtle polysemy in VerbNet:
             keep-15.2 is about storing, while fit-54.3 is about the
             possibility to store, ie. fitting. Since the alternations show
             this difference, the two senses are in VerbNet while they're only
             one sense in WordNet and OntoNotes. -->
        <role name='Destination' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='store.1a' vn='keep-15.2' sense='ok' alternations='ok' roles='more'>
        <!-- This is an interesting case of subtle polysemy in VerbNet:
             keep-15.2 is about storing, while fit-54.3 is about the
             possibility to store, ie. fitting. Since the alternations show
             this difference, the two senses are in VerbNet while they're only
             one sense in WordNet and OntoNotes. -->
        <role name='Destination' vn='Agent' />
        <role name='Patient' vn='Theme' />
    </lexie>
    <lexie name='thaw.1a' vn='other_cos-45.4-1' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='threaten.1' vn='amuse-31.1' sense='ok' alternations='more' roles='more'>
        <role name='Cause' vn='Stimulus' />
        <role name='Patient' vn='Experiencer' />
    </lexie>
    <lexie name='transport.1' vn='send-11.1' sense='ok' alternations='ok' roles='ok'>
        <role name='Patient' vn='Theme' />
        <role name='Destination' vn='Destination' />
        <role name='Source' vn='Initial_Location' />
        <role name='Cause' vn='Agent' />
    </lexie>
    <lexie name='vary.1' vn='calibratable_cos-45.6-1' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='warm.1a' vn='other_cos-45.4' sense='ok' alternations='more' roles='more'>
        <role name='Patient' vn='Patient' />
    </lexie>
    <lexie name='warm.1b' vn='other_cos-45.4' sense='ok'>
        <role name='Agent' vn='Agent' />
        <role name='Cause' vn='Agent' />
        <role name='Patient' vn='Patient' />
    </lexie>
</dico_verbnet_rolemapping>
